### PR TITLE
git-extra: offer an easy way to update an SDK via Pacman

### PR DESCRIPTION
**Pull request by dscho**
This PR adds the Batch file `update-via-pacman.bat` to the top-level directory of any Git for Windows SDK. This script will make it easier, hopefully, to update a local copy of the SDK.

cc @SteveALee

### CODE REVIEW

**Comment by PhilipOakley** [comment]
I had a read through and didn't see anything untoward, but then again I haven't actually tried it.

The one other point is "How to bootstrap this for existing users?" - The commit message, or PR message, should have some small note to the 'less gifted' SDK users, who already have the older SDK installed, as to how to pick up the bat file into their own setup.  

Once the PR is accepted new users should be just fine...

**Comment by SteveALee** [comment]
Looks good and works for me. It successfully updated the core and re ran to do rest.

A minor niggleif you run again and packman doesn't run the missing log seems to trip it up

```
 there is nothing to do
/c/Users/steve/.bashrc: line 29: cd: /c/projects/aim-web-app: No such file or directory
tail: cannot open 'var/log/pacman.log' for reading: No such file or directory
"Run Pacman again to upgrade the remaining (non-core) packages"
```

**Comment by SteveALee** [comment]
PS I can update the wiki page if you like when this is merged?

**Comment by dscho** [comment]
> /c/Users/steve/.bashrc: line 29: cd: /c/projects/aim-web-app: No such file or directory

What is in line 29 of that file?

**Comment by dscho** [comment]
> The one other point is "How to bootstrap this for existing users?" - The commit message, or PR message, should have some small note to the 'less gifted' SDK users, who already have the older SDK installed, as to how to pick up the bat file into their own setup.

@PhilipOakley I added this paragraph to the commit message:

> Existing users can copy the `update-via-pacman.bat` file directly into their SDK's top-level directory, or get it via `pacman -Sy git-extra` once https://github.com/git-for-windows/build-extra/pull/244 is merged.

**Comment by dscho** [comment]
> A minor niggleif you run again and pacman doesn't do anyhting the missing log seems to trip it up

@SteveALee you're right! I forgot two things:

- I forgot to use the absolute path for `/var/log/pacman.log` (in an earlier version, the script `cd`ed into the top-level directory of the SDK, but I figured that would no longer be necessary, so I removed it).
- You pointed out that there is a good chance that there is "nothing to do", in which case no needle is found. I tried to fix that, but have currently no good way to test this. Could I bother you with testing this again?

I force-pushed to address these two issues.

> PS I can update the wiki page if you like when this is merged?

That would be great, thank you!

**Comment by SteveALee** [comment]
@dscho 

>>    /c/Users/steve/.bashrc: line 29: cd: /c/projects/aim-web-app: No such file or directory

> What is in line 29 of that file?

Ah, sorry - simply a `cd` to the directory that no longer exists - I was lazy :)

**Comment by SteveALee** [comment]
> You pointed out that there is a good chance that there is "nothing to do", in which case no needle is found. I tried to fix that, but have currently no good way to test this. Could I bother you with testing this again?

Not quite there yet. Here's the output

```
:: Starting core system upgrade...
warning: msys2-runtime: ignoring package upgrade (2.11.2-1 => 3.0.4-1)
warning: msys2-runtime-devel: ignoring package upgrade (2.11.2-1 => 3.0.4-1)
 there is nothing to do
:: Starting full system upgrade...
warning: grep: local (3.1-1) is newer than msys (3.0-2)
warning: libgc: local (8.0.0-1) is newer than msys (7.6.8-1)
warning: libxml2: ignoring package upgrade (2.9.8-1 => 2.9.9-2)
warning: mingw-w64-i686-binutils: local (2.31.1-2) is newer than mingw32 (2.30-5)
warning: mingw-w64-x86_64-binutils: local (2.31.1-2) is newer than mingw64 (2.30-5)
warning: mingw-w64-x86_64-gcc: ignoring package upgrade (7.3.0-2 => 8.3.0-2)
warning: mingw-w64-x86_64-gcc-libs: ignoring package upgrade (7.3.0-2 => 8.3.0-2)
warning: mingw-w64-x86_64-osslsigncode: ignoring package upgrade (1.7.1-3 => 1.7.1-4)
 there is nothing to do
```

So that looks better - I assume those messages are due to the temp G4W version issue you mentioned elsewhere?

Actually, why does it say "nothong to do" when you use `-Syy` which I understand always refreshes? 
 
```
tail: cannot open '/var/log/pacman.log' for reading: No such file or directory
```

Hmmm. :(

```
warning: git-extra-1.1.359.febab20-1 is up to date -- reinstalling
```

What is you expecteation for where we run this script? The root of the SDK seems reasonable - but perhasp add a usage to the comments or script output?.

I was running in a cmd shell as it's a .bat (.cmd).

I just found out that I CAN run it in the SDK bash shell. I assumed I would not as autocomplete fails for .bat (that is tab after typing a few chars like `./aut` ) But it's fine if will run if you type in the full name (can we fix that?).

**Comment by dscho** [comment]
> So that looks better - I assume those messages are due to the temp G4W version issue you mentioned elsewhere?

Those messages are due to some packages having been available in MSYS2 at newer versions, but apparently no longer. No idea what's the story behind that.

> why does it say "nothong to do" when you use `-Syy` which I understand always refreshes?

`pacman -Syy` only makes sure that the databases (or package indices) are downloaded, even if `pacman` thinks that the local copies are up to date.

"Nothing to do" means that we have the newest versions of the installed packages.

So that is quite good!

> ```
> tail: cannot open '/var/log/pacman.log' for reading: No such file or directory
> ```
> 
> 
> Hmmm. :(

Can you verify that this file is indeed absent?

> What is you expectation for where we run this script? The root of the SDK seems reasonable - but perhasp add a usage to the comments or script output?.

It should not matter. `pacman` is supposed to take care of changing the working directory as needed.

> I was running in a cmd shell as it's a .bat (.cmd).

That's the right way to do it.

> I just found out that I CAN run it in the SDK bash shell.

But please don't! The entire idea of making this a `.bat` script is so that you do not have to run anything MSYS2-related (like the Git Bash), which could prevent a core update.

You see, `pacman` may overwrite `/usr/bin/msys-2.0.dll` with a newer version. That is specifically intended to work.

However, after that, the MSYS2 runtime has a problem with the tear-down of its POSIX emulation layer. Meaning: *any* MSYS2 program. Like `pacman`. And like `bash`!

Therefore: best not to call `pacman` from Bash.

**Comment by dscho** [comment]
I guess this PR is as good as it will ever get. Merging time!

**Pull request merged**
