### PR TITLE
More work on the `git-extra` package

### PR DESCRIPTION
**Pull request by dscho**
With these changes, we should be good to go as far as Git for Windows is concerned.

### CODE REVIEW

**Comment by dscho** [comment]
@sschuberth my current thinking is to just not care that `filesystem` and `pacman` hard-code the config files. I'd rather fix up after upgrades for the moment (which is essentially a `for f in /etc/*.pacsave; do mv -f $f ${f%.pacsave}; done && pacman -S --noconfirm git-extra`, i.e. force-reapplying `git-extra`'s post-install script). That also means that I would prefer to stop overriding `pacman` and `pacman-mirrors` in our Bintray again.

**Comment by nalla** [comment]
Glad I could help. Looks good.

**Comment by dscho** [comment]
@nalla thanks!

@t-b @sschuberth could please any of you review this and merge, or in the alternative comment? I am really waiting for this.

**Comment by t-b** [comment]
@dscho Sorry I will not find any time soon.

**Comment by dscho** [comment]
Okay, fine, I will merge it myself.

First I have to find a way to make the post-install script independent of the architecture for which it should be installed, though.

**Comment by dscho** [comment]
@sschuberth sorry, I know you want to review Pull Requests but I really need to move on with this.

**Comment by sschuberth** [comment]
> sorry, I know you want to review Pull Requests before merging but I really need to move on with this.

@dscho That's alright. If I exceed our agreed limit for replying to reviews and you deem a PR to be good just go ahead and merge.

**Pull request merged**
