### PR TITLE
update-via-pacman: add stage breaks in pacman output

### PR DESCRIPTION
**Pull request by PhilipOakley**
The pacman output presented a wall of text that can be difficult to understand when updates don't go to plan.

Provide clear stage breaks in the output stream to improve user experience. No functional changes whatsoever.

Signed-off-by: Philip Oakley <philipoakley@iee.email>

---
I've been that user ;-)

### CODE REVIEW

**Comment by PhilipOakley** [comment]
Apologies.
Looks like I edited the copy in the sdk top level and failed to correctly transfer those edits to the build-extra after manual testing.

**Comment by PhilipOakley** [comment]
Looks like my real mistake in the checks was the `Validating source files with sha256sums` so need to locate and update that [tomorrow].

**Comment by PhilipOakley** [comment]
Whilst I'd started my branch from `origin/main`, I hadn't fetch updates recently enough to catch the change in `git-credential-helper-selector.c`, with its adjacent sha256sum change. Fetched & rebased. Waiting for CI checks...

**Review by dscho — APPROVED** [review]
Technically, the comment "I've been that user" goes into the PR description, not in the commit message ;-)

**Comment by PhilipOakley** [comment]
> Technically, the comment "I've been that user" goes into the PR description, not in the commit message ;-)

It was this author's habit for patch submission ;-) 

Thank you for merging.

**Pull request merged**
