### PR TITLE
Update install.iss: rephrase menu item labels

### PR DESCRIPTION
**Pull request by ivadham**
Windows context menu:
- Git Bash Here -> Open Git Bash here
- Git GUI Here -> Open Git GUI here

P.S. Today I learned what DCO sign-off is. Thank you!

### CODE REVIEW

**Review by rimrul — CHANGES_REQUESTED** [review]
First things first: ignore the `missing dll` CI job failures, those are unrelated.

The change does what was discussed in https://github.com/git-for-windows/git/discussions/4477#discussioncomment-6263051, but that comment accidentally mislead you. These are the feature descriptions within the installer, not the text for the actual context menu entries. That text is defined [here](https://github.com/git-for-windows/build-extra/blob/833475c533087245c5bdbde3400f1c549ebe7f27/installer/install.iss#L3313) and [here](https://github.com/git-for-windows/build-extra/blob/833475c533087245c5bdbde3400f1c549ebe7f27/installer/install.iss#L3330).
Could I ask you to modify these two lines as well and then ammend the commit and force push?

**Comment by ivadham** [comment]
No worries. Thanks for the heads up!
Oh, shoot! I forgot to do DCO sign-off. I thought this was a one-time thing per PR.

**Comment by dscho** [comment]
> that comment accidentally mislead you

Ooops. Sorry!

**Comment by ivadham** [comment]
@rimrul, hey! Although I hate to disturb you by mentioning you, more than two weeks have passed since this "change request", and I have pushed the changes you asked for. It is done in **two** commits; maybe that's the reason why you have not been notified. Anyway, this PR requires a review. Thanks!

**Review by dscho — APPROVED** [review]
Nice work, thank you for following through with it!

**Comment by dscho** [comment]
/add release note bug The labels of the File Explorer menu items installed by the Git for Windows installer [have been aligned](https://github.com/git-for-windows/build-extra/pull/507) with what is customary ("Git Bash Here" instead of "Open Git Bash Here").

**Pull request merged**
