### PR TITLE
Fixed Typo

### PR DESCRIPTION
**Pull request by HyunseungLee-Travis**
The carriage return '#13' seemed to have erased 'e' at the end of 'are' and 'the'

[EDIT: removed template text that was supposed to be removed after reading]

### CODE REVIEW

**Comment by dscho** [comment]
Hmm. I am not sure. This is how that page looks here:



Are you saying that for you, the trailing `e`s are cut off? If so, this diff might pose a better solution:

```diff
diff --git a/installer/install.iss b/installer/install.iss
index 802cc7e2d..5d147dd0e 100644
--- a/installer/install.iss
+++ b/installer/install.iss
@@ -2017,7 +2017,7 @@ begin
     RdbDefaultBranch[DB_Unspecified].OnClick:=@DefaultBranchOptionChanged;
 
     // 2nd choice
-    RdbDefaultBranch[DB_Manual]:=CreateRadioButton(DefaultBranchPage,'Override the default branch name for new repositories','<RED>NEW!</RED> Many teams already renamed their default branches; common choices are'+#13+'"main", "trunk" and "development". Specify the name "git init" should use for the'+#13+'initial branch:',TabOrder,Top,Left);
+    RdbDefaultBranch[DB_Manual]:=CreateRadioButton(DefaultBranchPage,'Override the default branch name for new repositories','<RED>NEW!</RED> Many teams already renamed their default branches; common choices'+#13+'are "main", "trunk" and "development". Specify the name "git init" should use'+#13+'for the initial branch:',TabOrder,Top,Left);
     RdbDefaultBranch[DB_Manual].OnClick:=@DefaultBranchOptionChanged;
 
     // Text field for the overridden branch name
```

Over here, the result looks like this:

**Comment by dscho** [comment]
@HyunseungLee-Travis ping?

**Comment by dscho** [comment]
@HyunseungLee-Travis what's this? Has the problem gone away on your side by some miracle? Or was there something else?

**Comment by HyunseungLee-Travis** [comment]
I think your solution might be better than mine

**Comment by dscho** [comment]
Could you squash the two commits into a single one, and amend the commit message to explain the reason why `install.iss` was updated? Feel free to imitate 1db0a7911b6e1b97b8d98197c997afe4f12823df (which seems to have addressed a similar problem).

**Comment by HyunseungLee-Travis** [comment]
the final commit will be the latest one: eb579bb31306d7f4ec968ca769cf0c6452f9e088

**Comment by dscho** [comment]
> Could you squash the two commits into a single one

This is still needed.

> and amend the commit message

This, too.

> The sign-off is missing.

As well as this (see https://github.com/git-for-windows/build-extra/pull/360/checks?check_run_id=2983682878 for details, and https://github.com/git-for-windows/build-extra/blob/HEAD/pull_request_template.md#what-is-dco-sign-off--why-is-it-required for an explanation why this is required).

**Comment by dscho** [comment]
@HyunseungLee-Travis Is this still an issue with Git for Windows v2.33.0?

If so, I would like to ask for these changes to be rebased, and squashed into a single commit, with a commit message that reflects that we're rewrapping the message (not fixing a typo) and why, and with a real email address in the `Signed-off-by:` line.

Thank you in advance!

**Comment by HyunseungLee-Travis** [comment]
```
hint: Waiting for your editor to close the file... 
[main 2021-08-20T07:15:27.136Z] window: using vscode-file:// protocol and V8 cache options: bypassHeatCheck 
[main 2021-08-20T07:15:27.270Z] update#setState idle
[main 2021-08-20T07:15:27.277Z] update#ctor - startup checks only; automatic updates are disabled by user preference  
```

Github Desktop keeps telling me that automatic updates are disabled. How can I fix this? I tried rebasing by running `git rebase -i main` but it seems to not work.

**Comment by dscho** [comment]
> Github

It's an upper-case "H", there's no "th" sound in that word.

> Desktop keeps telling me that automatic updates are disabled. How can I fix this?

Wrong project to ask this :smile:

> I tried rebasing by running git rebase -i main but it seems to not work.

If you ask for assistance, more details would probably help. An interactive rebase can go wrong in a million ways. It's hard to guess which one you encountered.

**Pull request closed without merging**
