### PR TITLE
Add to installer Tig

### PR DESCRIPTION
**Pull request by Kirill**
Add to installer Tig: text-mode interface for Git
https://github.com/jonas/tig

### CODE REVIEW

**Comment by dscho** [comment]
@Kirill thank you very much for working on this.

As promised, I want to help you get this included. A couple of things would still need to be done:

- have you verified that `tig` works in the built installer?
- did you build an installer without `tig` first and have the file sizes of the installer?
- if so, could you please include both bits of information in the commit message? (`git commit --amend` followed by `git push --force` is your friend...)
- could you please sign off your commit (essentially stating that yes, you are entitled to publish this patch under the GPLv2)? (`git commit --amend -s` followed by `git push --force` is your friend...)

**Comment by Kirill** [comment]
@dscho 
Sorry.
1. Yes. git version 2.14.1.windows.1.1017.gb5915c6ae8

2. w/o: 47 160 645; with tig: 47 275 703

**Comment by dscho** [comment]
Excellent! This is really exciting, well done!

**Comment by Kirill** [comment]
@dscho Thanks

**Pull request merged**
