### PR TITLE
Net installer fixes

### PR DESCRIPTION
**Pull request by sschuberth**

### CODE REVIEW

**Comment by dscho** [comment]
Thanks!

**Comment by sschuberth** [comment]
Ah, crap, I just pushed https://github.com/git-for-windows/build-extra/commits/net-installer-fixes2 which splits out the change to make "-c" an option to clone as a separate commit. For the fun of it, should we revert the merge from the GitHub web interface and merge a new PR?

**Comment by dscho** [comment]
If you want. I'm fine with the status quo, there are bigger fish to fry, still...

**Comment by sschuberth** [comment]
Ok, no, let's save the work. I'll just create a dummy PR and close it immediately again for documentation purposes, in particular the commit message of ee548ec1e2adecce928d55fda3e1cab8ee6cc919.

**Pull request merged**
