### PR TITLE
Sanitize Pacman databases while adding new packages

### PR DESCRIPTION
**Pull request by dscho**
Git for Windows' Pacman package databases are updated only via automated builds. In at least one of them, bogus entries were added (see git-for-windows/git#3034 and git-for-windows/git#3035). This PR adjusts the automated builds so that that won't happen again (or at least so that it will self-heal).

### CODE REVIEW

**Comment by dscho** [comment]
@elieux could you please verify that this works for you?

**Comment by dscho** [comment]
Oh well, I think I'll just have to try it ;-)

**Comment by dscho** [comment]
Seems to have worked.

**Comment by elieux** [comment]
Sorry, I do these things in spurts, I only got to reading responses today.

**Comment by elieux** [comment]
Looks like everything is clean now.

**Comment by dscho** [comment]
> 
> 
> Looks like everything is clean now.

Thanks for checking!

**Pull request merged**
