### PR TITLE
Documented --cd, --no-cd and the HOME environment variable

### PR DESCRIPTION
**Pull request by sukiletxe**

### CODE REVIEW

**Comment by sukiletxe** [comment]
Please, could you specify the line numbers, rather than adding comments? I'm totally blind and unfortunately I can't read where your comments belong to.
Also, I'm quite newbie to github, is it okay if I use git commmit --ammend?
Thanks.

**Comment by sukiletxe** [comment]
Probably this clarification is not necessary, but just in case: I mean, could you specify the line numbers that need to be changed in the comment body, rather than adding line comments?

**Comment by sukiletxe** [comment]
Okay, I was looking in the wrong place for the line comments. I can see them and I will fix them in a few hours.
Thanks.

**Comment by sukiletxe** [comment]
I've fixed those issues.
Thanks.

**Comment by dscho** [comment]
> Please, could you specify the line numbers, rather than adding comments? I'm totally blind and unfortunately I can't read where your comments belong to.

Oops, sorry! I will try to quote better in the future, thanks for pointing that out.

> is it okay if I use git commmit --ammend?

Yes, the rule of thumb in the Git for Windows project is that `master` must *never* be rewritten (which `-amend` does, it rewrites commits), but topic branches are fair game.

**Comment by dscho** [comment]
Thanks!

**Pull request merged**
