### PR TITLE
Replace usage of .bat with .exe

### PR DESCRIPTION
**Pull request by pdelre**
It appears the README has diverged from the packaged portable files. Instead of `git-bash.bat` and `git-cmd.bat` existing, it is now `git-bash.exe` and `git-cmd.exe` in PortableGit-2.3.5.8-dev-preview-64-bit.

### CODE REVIEW

**Comment by sschuberth** [comment]
Thanks! In fact there are some more places that need to get fixed, but I'll handle them separately.

**Comment by sschuberth** [comment]
> In fact there are some more places that need to get fixed.

Actually, it's only one more place: Would mind removing the files from `.gitignore`, too?

**Comment by pdelre** [comment]
Done!

**Comment by dscho** [comment]
> But can we have a sign-off in the commit message, please?

@pdelre what @sschuberth referred to was the habit we picked up from the Git project to request a [Developer's Certificate of Origin](https://github.com/git-for-windows/git/blob/v2.3.5/Documentation/SubmittingPatches#L234-L277).

Would you mind adding that (easiest method: `git rebase -i HEAD~2`, then replace the two `pick` with `edit` commands and quit the editor, then call `git commit --amend -s && git rebase --continue && git commit --amend -s && git rebase --continue && git push origin +HEAD`)?

**Comment by pdelre** [comment]
Sure @dscho. I had been editing in github's UI, but will modify the commits after cloning locally.

**Comment by dscho** [comment]
Thanks, @pdelre!

**Comment by pdelre** [comment]
@sschuberth @dscho I believe the signed-off-by is all set.

**Comment by sschuberth** [comment]
Thanks!

**Pull request merged**
