### PR TITLE
Support generating NuGet packages of Git for Windows

### PR DESCRIPTION
**Pull request by dscho**
We steal heavily from ourselves here...

Please note that the Install.ps1 script is only called if the NuGet
package is installed inside Visual Studio (and not if installed via
nuget.exe; this is a bug in nuget.exe as of time of writing).

Therefore, the user should still call tools\post-install.bat manually
or start tools\git-bash.exe once before doing anything else, if
nuget.exe is used to install this package.

Signed-off-by: Johannes Schindelin <johannes.schindelin@gmx.de>

### CODE REVIEW

**Comment by whoisj** [comment]
Generally looks good.

I'm surprised there's not a way to do all / most of this via args to nuget.exe.

**Comment by dscho** [comment]
> I'm surprised there's not a way to do all / most of this via args to nuget.exe.

Heh. Would be too easy.

Another question: do you think *GitForWindows* is a good name, or should it be *Git*? (*PortableGit* is unfortunately [taken by somebody else](https://www.nuget.org/packages/PortableGit/))

**Comment by whoisj** [comment]
I'd go with something like `Git.Windows.Portable`. This allows for `Git.Linux`, `Git.Osx`, etc. Additionally, it allows for other future flavors of "Git for Windows". Perhaps `Git.Windows.UberStyle` or what have you.

**Comment by dscho** [comment]
AFAICT on NuGet the names are not really hierarchical. And GitForWindows is not really the same as Git for Linux (because we have to ship *so* much infrastructure *just* to make Git work alright). So I kept the original name.

**Pull request merged**
