### PR TITLE
avoid unexpected behavior (in particular error messages) if user remapped g`

### PR DESCRIPTION
**Pull request by Konfekt**
Same issue as in [Opensuse](https://bugzilla.opensuse.org/show_bug.cgi?id=1190332)

### CODE REVIEW

**Comment by rimrul** [comment]
Why do you submit this PR to change that line, just to submit a PR 7 minutes later that removes the line entirely? (#380)

**Comment by Konfekt** [comment]
To give you the choice. Though I prefer the latter PR, the former is more conservative and therefore the maintainer could prefer the former.

**Comment by dscho** [comment]
> 
> 
> Same issue as in [Opensuse](https://bugzilla.opensuse.org/show_bug.cgi?id=1190332)

And what would that be? Do you expect every reader to follow the link and then summarize the issues for themselves?

BTW You misspelled openSUSE... And your patch is not signed-off.

And the commit message is in want of being improved in other ways, too. To summarize

- Since `build-extra` contains many more things than just the `vimrc`, the commit message should start with `vimrc:`.
- The problem which is fixed by this commit needs to be described properly.
- The link should not be formatted as Markdown but as plain text instead.
- When linking to the openSUSE site, the name has to be spelled correctly.
- The commit needs to be signed off.

Once those things are done, please force-push, and the PR can be merged.

**Comment by Konfekt** [comment]
The [force push](https://github.com/git-for-windows/build-extra/commit/5d85e8b112533d40d10ab38129c545d6ad5b490d)automatically closed this pull request.

**Comment by Konfekt** [comment]
Thank you for the detailed instructions which I hope to have followed.

Regarding

> Do you expect every reader to follow the link and then summarize the issues for themselves?

I hoped that the title summarizes the issue but forgot to mention Vim, and regarding

>BTW You misspelled openSUSE... And your patch is not signed-off.

Proper nouns start with capital letters, though the company spells its name differently.

**Comment by rimrul** [comment]
>The force pushautomatically closed this pull request.

You've certainly done something interesting, but I don't quite know how.
You managed to create a copy of `6ca08cd` without a parent (`6a6bf1a`) and rebased your patch on top of that. To GitHub this looks like there is no common history between your patch and our `main` branch, wich is why I can't even reopen it... I'll take a look how to fix this.

**Comment by dscho** [comment]
> 
> 
> > The force pushautomatically closed this pull request.
> 
> You've certainly done something interesting, but I don't quite know how.
> You managed to create ~a copy of `6ca08cd` without a parent (`6a6bf1a`)~ a single commit containing the state of the repository as of [6ca08cd](https://github.com/git-for-windows/build-extra/commit/6ca08cdeb4bbb4f7fd0130ab280a8463d5aaf994) and the commit message and author of [6ca08cd](https://github.com/git-for-windows/build-extra/commit/6ca08cdeb4bbb4f7fd0130ab280a8463d5aaf994) ([6a6bf1a](https://github.com/git-for-windows/build-extra/commit/6a6bf1ad6ea923db80329a65d18667c4039ce927)) and rebased your patch on top of that. To GitHub this looks like there is no common history between your patch and our `main` branch, wich is why I can't even reopen it... I'll take a look how to fix this.

I think what happened might have been a shallow clone, followed by a `git rebase --root`...

**Comment by dscho** [comment]
The commit message unfortunately repeats a lot of what the patch does, i.e. it answers the questions "How?" and to a minor degree "What?". What I am _still_ missing, however, is more of an answer to "Why?" including an explanation how one would override `g` and _why one would override it_.

After that, we can easily just cherry-pick it, but the commit message should be improved so that future readers (myself included) do not have to puzzle so much.

**Comment by Konfekt** [comment]
A [new commit message](https://github.com/Konfekt/build-extra/commit/c6305a7acd15dffe24be42cd7017b7e5e47c993d) taking into account your indications

**Comment by dscho** [comment]
I cherry-picked it as 18645b706.

**Pull request closed without merging**
