### PR TITLE
please.sh: drop a lot of functionality that is no longer used

### PR DESCRIPTION
**Pull request by dscho**
This is in response to [a comment that asked whether `release` is still in use](https://github.com/git-for-windows/build-extra/pull/452#discussion_r1053792396).

### CODE REVIEW

**Review by dennisameling — APPROVED** [review]
This is _super_ helpful for my follow-up work to prevent me from updating things that are no longer used. Thank you!

**Comment by dscho** [comment]
@dennisameling FYI I added a commit intended to trigger the `sdk-artifacts` build so that I do not accidentally remove any really crucial functionality. Knock on wood...

**Comment by dscho** [comment]
I also kicked off a full `git-artifacts` run: https://github.com/dscho/git-sdk-64/actions/runs/3757109515/jobs/6383945295

**Comment by dscho** [comment]
> I also kicked off a full `git-artifacts` run: https://github.com/dscho/git-sdk-64/actions/runs/3757109515/jobs/6383945295

[I'm glad I did!](https://github.com/dscho/git-sdk-64/actions/runs/3757109515/jobs/6383945295#step:6:1052)

**Comment by dscho** [comment]
[The `git-artifacts` run worked](https://github.com/dscho/git-sdk-64/actions/runs/3758811509).

I'll merge it when I'm back.

**Comment by dscho** [comment]
It is time to merge this, I think.

**Pull request merged**
