### PR TITLE
 Add a script for installing and updating Git-for-windows on Msys2 ( including Git-for-windows ) and Cygwin

### PR DESCRIPTION
**Pull request by 391861737**
As adviced by @dscho in the thread git-for-windows/git#1335, I committed this PR to find a home for these scripts which might and are glad to help others

The `gitupdate` could install and update the `git-for-windows`'s binary and copy all necessary files on msys2 without messing up your msys2 due to the already installed msys2 environment which has already contained most of the files which are needed by the `git-for-windows`'s binary files. This script will check the latest released version of the git-for-windows via its tags page on Github and then download it using `wget` or `curl` (*if wget cound not be found nor installed by Pacman*)... and then extract files into `/tmp` from the downloaded installer using `innounp`, copy necessary files and clean up all the temp files at last.

The `upkit` is a tool kit for `gitupdate` containing some reusable functions, this might be useful if someone wants to write a similar script. I personally wrote a script to install and update the latest `metasploit-framework` using `upkit` as well. (*If anyone is interested, I could create a public repo and share that*)

This might work on cygwin, but not assured.

Signed-off-by: liuxy <391861737@qq.com>

### CODE REVIEW

**Comment by dscho** [comment]
Two questions:

1) Would it be possible to find a better home for that script? I mean, if this is intended to be installed together with Git for Windows, or with Portable Git, then it won't be found if it is in `build-extra`.
2) I cannot accept a PR with binaries. It is one thing to install it via `pacman` in a script, it is a totally different thing to accept an `.exe` from an untrusted source... Maybe you want to make sure that the script downloads the `innounp.exe` file (actually the `.tar.xz` one) from the Pacman repository?

**Comment by 391861737** [comment]
> Two questions:
> 
> 1. Would it be possible to find a better home for that script? I mean, if this is intended to be installed together with Git for Windows, or with Portable Git, then it won't be found if it is in `build-extra`.
> 2. I cannot accept a PR with binaries. It is one thing to install it via `pacman` in a script, it is a totally different thing to accept an `.exe` from an untrusted source... Maybe you want to make sure that the script downloads the `innounp.exe` file (actually the `.tar.xz` one) from the Pacman repository?

1. I'm not sure... my intention is just to follow your advice to give it a home here, I comprehended your advice in the other thread as that somehow this script might not as useful in the `git` repo. But if it does, I'll be glad to submit a PR there...
And if it goes that way, I might need to adjust these scripts to adapt both `mingw32` / `mingw64` environments... that would take some time. Any suggestions or advice are appreciated.
2. The `innounp.exe` is written and built by Delphi, and this makes it hard to create a package in the Pacman repository according to my knowledge(*msys2 needed the package to be reproducible, and it's hard to achieve without a proper compiler to compile `pascal`*). But I could just download the `Git-2.23.0-64-bit.tar.bz2` instead of the installer, it's just bigger in size, but not a problem...

**Comment by 391861737** [comment]
@dscho If it's not too late, may I ask where may I submit these scripts, here or the repo  `git-for-windows/git`?

**Comment by dscho** [comment]
Sorry for the delay in answering; I've been a bit busy with preparing Git for Windows v2.24.0-rc0 (and it is still not finished, I am waiting for the automation to fail _again_ so that I can fix _yet another_ problem...).

> > Two questions:
> > 
> > 1. Would it be possible to find a better home for that script? I mean, if this is intended to be installed together with Git for Windows, or with Portable Git, then it won't be found if it is in `build-extra`.
>
> 1. I'm not sure... my intention is just to follow your advice to give it a home here, I comprehended your advice in the other thread as that somehow this script might not as useful in the `git` repo. But if it does, I'll be glad to submit a PR there...
>
>   And if it goes that way, I might need to adjust these scripts to adapt both `mingw32` / `mingw64` environments... that would take some time. Any suggestions or advice are appreciated.

Oh, sorry, I think this is the correct repository. But I thought your script was meant to be run in a fully populated Git for Windows SDK? If so, it would probably make sense to install it as part of the `git-extra` package, whose contents can be found in this repository's `git-extra/` subdirectory.

> > 2. I cannot accept a PR with binaries. It is one thing to install it via `pacman` in a script, it is a totally different thing to accept an `.exe` from an untrusted source... Maybe you want to make sure that the script downloads the `innounp.exe` file (actually the `.tar.xz` one) from the Pacman repository?
> 
> 2. The `innounp.exe` is written in and built by Delphi, and this makes it hard to create a package in the Pacman repository according to my knowledge(_msys2 needed the package to be reproducible, and it's hard to achieve without a proper compiler to compile `pascal`_). But I could just download the `Git-2.23.0-64-bit.tar.bz2` instead of the installer, it's just bigger in size, but not a problem...

Silly question: why not just run the Portable installer in silent mode?

**Comment by 391861737** [comment]
Thank you for your hard-working `Git-for-windows` to bring us a great experience in using git on windows, it's a great thing for all developers! Very great work!
> > > Two questions:
> > > 
> > > 1. Would it be possible to find a better home for that script? I mean, if this ...
> > 
> > 
> > 
> > 1. I'm not sure... my intention is just to follow your advice to give it a home ...
> > 
> > 
> 
> Oh, sorry, I think this is the correct repository. But I thought your script was meant to be run in a fully populated Git for Windows SDK? If so, it would probably make sense to install it as part of the `git-extra` package, whose contents can be found in this repository's `git-extra/` subdirectory.

To make it work, one of the executables of `wget` or `curl` is needed. As the `curl` is now included in Windows 10's system32 folder from **1803** and also included in `/mingw64/bin`, this script could work either.

> > > 1. I cannot accept a PR with binaries. It is one thing to install it via `pacman` ...
> > 
> > 
> > 
> > 1. The `innounp.exe` is written in and built by Delphi, and this makes it hard ...
> 
> Silly question: why not just run the Portable installer in silent mode?

Whoa, I missed that simple solution... I didn't even notice that the self-extractable 7z package could do that kind of thing. that's a new thing I've learned today, thank you! I'll try that out in a few days.

**Comment by dscho** [comment]
> Thank you for your hard-working on `Git-for-windows` to bring us a great experience in using `Git` on windows, it's a great thing for all developers! **A great work!**

You're welcome!!!

> To make it work, one of the executables of `wget` or `curl` is needed. As the `curl` is now included in Windows 10's system32 folder from **1803** and also included in `/mingw64/bin`, this script could work either.

Excellent.

> > why not just run the Portable installer in silent mode?
> 
> Whoa, I missed that simple solution... I didn't even notice that the self-extractable 7z package could do that kind of thing. that's a new thing I've learned today, thank you! I'll try that out in a few days.

Perfect. Please do let us know how that goes.

**Comment by 391861737** [comment]
@dscho 
Hi there, it's been slightly busy lately, so I finally get this done... And also have it tested on `Msys2 32 bit`, `Msys2 64 bit`, `Cygwin 64 bit` and `Git for Windows 64 bit` in my `Windows Sandbox`.
With my latest changes, people could easily get or update `Git for Windows` on there `Msys2` or `Cygwin`  platform via `curl https://raw.githubusercontent.com/git-for-windows/build-extra/gitupdate/git-extra/getgit | bash` after the PR is merged.

So here's a question, is it worth to put an instruction about this feature in the readme?

**Comment by dscho** [comment]
> it's been slightly busy lately, yet I finally get this done ( **thanks to my weekend and the support from my wife, it is supposed to be me and her taking care of our baby together** )...

Oh, now I feel bad! Do go and spend time with your family, I would suggest. Git for Windows will still be there when you _actually_ have time to work on it.

> So here's a question, is it worth to put an instruction about this feature in the readme?

Sure, but please do not feel any pressure to add that!

**Comment by 391861737** [comment]
> > So here's a question, is it worth to put an instruction about this feature in the readme?
> 
> Sure, but please do not feel any pressure to add that!

Could not find a sensible section to put in the readme, so I finally added an introduction in the [wiki](https://github.com/git-for-windows/git/wiki/Install-or-update-inside-Msys2,-Cygwin-or-Git-for-windows-itself). :P

**Comment by dscho** [comment]
> I could not find a sensible section to put in the readme, so I finally added an introduction in the [wiki](https://github.com/git-for-windows/git/wiki/Install-or-update-inside-Msys2,-Cygwin-or-Git-for-windows-itself).

That makes a lot of sense to me! Thank you!

**Comment by 391861737** [comment]
> > I could not find a sensible section to put in the readme, so I finally added an introduction in the [wiki](https://github.com/git-for-windows/git/wiki/Install-or-update-inside-Msys2,-Cygwin-or-Git-for-windows-itself).
> 
> That makes a lot of sense to me! Thank you!

My pleasure!

**Comment by elieux** [comment]
Hey, @sinloss. After discussing this installation method on https://gitter.im/msys2/msys2, I would like to ask if you'd be okay with me reorganizing your wiki article to better separate the *How to* instructions from the rest.

**Comment by sinloss** [comment]
> Hey, @sinloss. After discussing this installation method on [Gitter](https://gitter.im/msys2/msys2), I would like to ask if you'd be okay with me reorganizing your [wiki article](https://github.com/git-for-windows/git/wiki/Install-or-update-inside-MSYS2,-Cygwin-or-Git-for-windows-itself) to better separate the _How to_ instructions from the rest.

Sure! Of course.

**Pull request merged**
