### PR TITLE
git-extra: include some usefull sdk-aliases

### PR DESCRIPTION
**Pull request by nalla**
For housekeeping the _Git for Windows SDK_ installation it would be useful
to have some common pacman snipplets right there to be used. Lets
introduce those snipplets in the build-extra repository.

### CODE REVIEW

**Comment by dscho** [comment]
Whoops, I missed that you updated the pull request, sorry.

But now I have an additional idea, please bear with me for a moment. I use tab-completion heavily, and having a `pacman-mirror.sh` and a `pacman-housekeeper.sh` in the same directory would require a couple more keystrokes from my side than I would like. How about renaming `pacman-mirror.sh` to `pacman-helper.sh` and then just adding the new subcommands `disowned-dirs`, `disowned-files` and `remove-orphans` to the same script?

What do you think?

**Comment by nalla** [comment]
Sounds like a plan. I'm on it.

**Comment by dscho** [comment]
Thanks!

**Comment by dscho** [comment]
Thanks @nalla! I unfortunately only get notified when a new comment is available, not when the branch was force-pushed. Would you terribly mind giving me a quick ping when you addressed my two last nit-picks?

**Comment by nalla** [comment]
@dscho ping

**Comment by dscho** [comment]
Perfect, thanks!

(Just out of curiosity: what was wrong with `echo` that it needed to be replaced by a `printf`?)

**Comment by nalla** [comment]
mainly because of the `\n` in the usage string.
```
$ echo "test\ntest"
test\ntest

$ printf "test\ntest"
test
test
```

**Comment by dscho** [comment]
Ah! Thanks!

**Pull request merged**
